##########################
# Conda environment for diagnostics step
# Author: Julian Bolivar
# Date: 2023/06/18
# Version: 1.0.0
##########################
name: diagnostics
channels:
  - conda-forge
  - defaults
dependencies:
# main system packets
  - python=3.8.16
  - mlflow=2.4.0
  - pip>=23.1.2
