##########################
# Conda environment for training step
# Author: Julian Bolivar
# Date: 2023-06-14
# Version: 1.0.0
##########################
name: training
channels:
  - conda-forge
  - defaults
dependencies:
# main system packets
  - python=3.8.16
  - mlflow=2.4.0
  - pip>=23.1.2
# data science packets
  - numpy=1.24.3
  - pandas=2.0.1
  - scikit-learn=1.2.2
