##########################
# Conda environment for reporting step
# Author: Julian Bolivar
# Date: 2023/06/18
# Version: 1.0.0
##########################
name: reporting
channels:
  - conda-forge
  - defaults
dependencies:
# main system packets
  - python=3.8.16
  - mlflow=2.4.0
  - pip>=23.1.2
# data science packets
  - numpy=1.24.3
  - pandas=2.0.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - statsmodels=0.13.5
  - matplotlib=3.7.1
  - pillow=9.5.0
  - seaborn=0.12.2
