##########################
# Versions updated to last on conda-forge and pypi
# Author: Julian Bolivar
# Date: 2023-06-07
# Version: 1.1.0
##########################
name: eda
channels:
  - conda-forge
  - defaults
dependencies:
# main system packets
  - python=3.8.16
  - jupyterlab=4.0.0
# data science packets
  - numpy=1.24.3
  - pandas=2.0.1
  - scikit-learn=1.2.2
  - scipy
  - ydata-profiling=4.2.0
# Packets managment and version control
  - pip>=23.1.2
# misselanues packets
  - threadpoolctl=3.1.0
  - matplotlib
  - pillow
  - ipywidgets
  - pyarrow
