##########################
# Conda environment for deployment
# Author: Julian Bolivar
# Date: 2023-06-14
# Version: 1.0.0
##########################
name: deployment
channels:
  - conda-forge
  - defaults
dependencies:
# main system packets
  - python=3.8.16
  - mlflow=2.4.0
  - pip>=23.1.2
