##########################
# Conda environment for main pipeline
# Author: Julian Bolivar
# Date: 2023/06/19
# Version: 1.0.0
##########################
name: main
channels:
  - conda-forge
  - defaults
dependencies:
# main system packets
  - python=3.8.16
  - mlflow=2.4.0
  - hydra-core=1.3.2
  - pip>=23.1.2
# PIP Dependencies
  - pip: 
      - hydra-joblib-launcher==1.2.0


