##########################
# Versions updated to last on conda-forge and pypi
# Author: Julian Bolivar
# Date: 2023-06-11
# Version: 1.0.0
##########################
name: ingestion
channels:
  - conda-forge
  - defaults
dependencies:
# main system packets
  - python=3.8.16
  - mlflow=2.4.0
  - pip>=23.1.2
  - hydra-core=1.3.2
# data science packets
  - pandas=2.0.1
