##########################
# Conda environment for {{cookiecutter.step_name}}
# Author: {{cookiecutter.author_name}}
# Date: {{cookiecutter.date}}
# Version: {{cookiecutter.version}}
##########################
name: {{cookiecutter.step_name}}
channels:
  - conda-forge
  - defaults
dependencies:
# main system packets
  - python=3.8.16
  - mlflow=2.4.0
  - pip>=23.1.2
